'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { cn } from '@/lib/utils'

export default function DisclaimerPage() {
  const router = useRouter()
  const [agreed, setAgreed] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleAccept() {
    if (!agreed) return
    setLoading(true)
    setError(null)

    try {
      const res = await fetch('/api/disclaimer', { method: 'POST' })
      if (!res.ok) throw new Error('Failed to record acceptance')
      router.push('/dashboard')
      router.refresh()
    } catch {
      setError('Something went wrong. Please try again.')
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-bg flex flex-col items-center justify-center px-4 py-12">
      <div className="w-full max-w-2xl">
        {/* Header */}
        <div className="text-center mb-10">
          <h1 className="font-display text-5xl tracking-widest text-gold mb-2">AIQ</h1>
          <p className="font-serif text-text-secondary tracking-wide">ADVISORS</p>
        </div>

        {/* Disclaimer Card */}
        <div className="bg-bg-secondary border border-border-gold rounded-lg overflow-hidden">
          {/* Card Header */}
          <div className="bg-gold/10 border-b border-border-gold px-8 py-5">
            <h2 className="font-serif text-xl text-gold">
              Before We Begin — Important Notice
            </h2>
            <p className="text-text-secondary text-sm mt-1">
              Please read carefully. This acknowledgment is required to use AIQ Advisors.
            </p>
          </div>

          {/* Disclaimer Text */}
          <div className="px-8 py-6 space-y-5 text-text-secondary text-sm leading-relaxed">
            <section>
              <h3 className="text-text-primary font-semibold mb-2">Strategic Guidance, Not Professional Advice</h3>
              <p>
                AIQ Advisors provides strategic information and educational guidance about AI and blockchain technology adoption. The content generated by our AI advisors — including the AIQ Legal Advisor and AIQ Real Estate Advisor — does <strong className="text-text-primary">not</strong> constitute licensed legal advice, investment advice, financial advice, or any other form of professional advisory service regulated by law.
              </p>
            </section>

            <section>
              <h3 className="text-text-primary font-semibold mb-2">No Attorney-Client or Advisor-Client Relationship</h3>
              <p>
                Using AIQ Advisors does not create an attorney-client relationship, fiduciary relationship, or any other professional relationship. Our AI advisors are tools for exploration and strategic thinking — not substitutes for qualified licensed professionals.
              </p>
            </section>

            <section>
              <h3 className="text-text-primary font-semibold mb-2">Financial & Investment Information</h3>
              <p>
                Any information relating to cryptocurrency, digital assets, real estate investment, or financial strategy is provided for educational and informational purposes only. This is <strong className="text-text-primary">not</strong> investment advice. Past performance of any asset or strategy does not indicate future results. All investments carry risk, including complete loss of principal.
              </p>
            </section>

            <section>
              <h3 className="text-text-primary font-semibold mb-2">Jurisdiction & Regulatory Variance</h3>
              <p>
                Laws, regulations, and professional standards vary significantly by jurisdiction. Information provided may not reflect the laws or requirements applicable in your location. Always verify information with qualified professionals in your jurisdiction before taking action.
              </p>
            </section>

            <section>
              <h3 className="text-text-primary font-semibold mb-2">AI Limitations</h3>
              <p>
                AI systems can produce inaccurate, incomplete, or outdated information. Do not rely solely on AIQ Advisors for decisions with material legal, financial, or professional consequences. Always verify critical information from authoritative sources.
              </p>
            </section>

            <div className="bg-gold/5 border border-border-gold rounded px-4 py-3">
              <p className="text-text-primary text-xs">
                By continuing, you acknowledge that you have read, understood, and agree to these terms, and that you will consult appropriately qualified professionals for decisions in your specific circumstances.
              </p>
            </div>
          </div>

          {/* Acceptance */}
          <div className="px-8 pb-8 space-y-5">
            <label className="flex items-start gap-3 cursor-pointer group">
              <div className="relative mt-0.5 flex-shrink-0">
                <input
                  type="checkbox"
                  checked={agreed}
                  onChange={(e) => setAgreed(e.target.checked)}
                  className="sr-only"
                />
                <div
                  className={cn(
                    'w-5 h-5 rounded border-2 transition-all duration-200 flex items-center justify-center',
                    agreed
                      ? 'bg-gold border-gold'
                      : 'bg-transparent border-border group-hover:border-gold/50'
                  )}
                >
                  {agreed && (
                    <svg className="w-3 h-3 text-bg" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                  )}
                </div>
              </div>
              <span className="text-text-secondary text-sm leading-snug group-hover:text-text-primary transition-colors">
                I have read and understand this notice. I agree that AIQ Advisors provides strategic guidance only, not professional advice, and I will consult qualified professionals for decisions in my specific circumstances.
              </span>
            </label>

            {error && (
              <div className="bg-red-950/30 border border-red-800/50 rounded px-4 py-3 text-red-400 text-sm">
                {error}
              </div>
            )}

            <button
              onClick={handleAccept}
              disabled={!agreed || loading}
              className={cn(
                'w-full py-4 font-display tracking-widest text-lg rounded transition-all duration-200',
                agreed && !loading
                  ? 'bg-gold text-bg hover:bg-gold-light cursor-pointer'
                  : 'bg-border text-text-muted cursor-not-allowed'
              )}
            >
              {loading ? 'CONFIRMING...' : 'I UNDERSTAND — ENTER AIQ ADVISORS'}
            </button>
          </div>
        </div>

        <p className="text-center text-text-muted text-xs mt-6">
          AIQ Industries LLC · Version 1.0
        </p>
      </div>
    </div>
  )
}
